[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 2 0 25 25]J'ai acheté les ingrédients pour préparer un sauté de poulet aujourd'hui, mais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 1 0 0 2 0 0]J'en ai peut-être trop pris. Je crois que j'ai eu les yeux plus gros que le ventre.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 1 0 0 3 0 0]J'ai toujours des restes. Et toi, [uf 4 2] ? Est-ce que t'es du genre à avoir un bon appétit ?[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]J'ai un appétit de moineau.[e]
[uf 0 5 65278][uf 2 1]Je mange comme quatre.[e]
[uf 0 5 65278][uf 2 1]Ça dépend de ce que je mange...[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 2 1 25 25]Sérieux ? Mais t'es en pleine croissance, non ? Je pensais que tu serais du genre à mieux manger.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 159 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 2 3 25 25]Mais bon, c'est vrai que tu es vraiment mince, donc ça se tient.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 2 0 25 25]Hmm... Peut-être que ça risque de te faire un peu trop à manger aujourd'hui, du coup.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 2 1 25 25]Oooh, je vois que tu manques pas d'appétit ! C'est ton jour de chance, parce qu'il y aura largement de quoi manger ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 159 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 2 3 25 25]J'espère que ce sera bon, mais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 159 65535 0 0][uf 3 1 1 0 0 9 0 0]Ne t'emballe pas trop, OK ? Ça fait un moment que je n'ai pas cuisiné.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 159 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 2 6 25 25]Je n'ai même pas encore commencé à cuisiner et tu t'inquiètes déjà ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 159 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 2 3 25 25]Je suis sûre qu'un bon petit plat saurait te convaincre, mais ne t'attends pas à quelque chose d'extraordinaire non plus...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 2 0 25 25]Hmm... Laisse-moi m'excuser à l'avance.[n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 2 1 25 25]Bon, dans tous les cas... ce sera riche en nutriments, donc t'en fais pas pour ça ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 14 0 0]Il n'y a rien de plus important que la santé, hein ? Donc je me suis dit qu'il fallait faire attention à ce qu'on mange.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 15 0 0]Et si en plus on peut perdre du poids au passage, d'une pierre deux coups... mais bon, on verra ça plus tard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 16 0 0]Bref, qu'est-ce que tu dirais de commencer par les légumes ? [uf 4 2], est-ce que tu pourrais couper les tomates ?[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]J'ai préparé un sauté de poulet avec Yukari...[n][uf 1 1][e]

[msg MSG_007_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 159 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 2 10 25 25]Arg...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 159 65535 0 0][uf 3 1 1 0 0 18 0 0]J'ai choisi du poulet parce que c'était la viande la moins chère et ce qu'il y a de mieux pour la santé apparemment, mais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 159 65535 0 0][uf 3 1 1 0 0 19 0 0]Je trouve ça sec... OK, vraiment sec. J'ai l'impression de manger de la semelle...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 10 159 65535 0 0][uf 3 1 1 0 0 20 0 0]Pff... Je m'y attendais pas. C'est rare que je foire ce genre de trucs...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 159 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 2 2 25 25]H-Hé ! Tu me crois pas ? Je suis sérieuse ![n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 159 65535 0 0][uf 3 1 1 0 0 22 0 0]Je me rattraperai la prochaine fois, donc il va falloir qu'on cuisine à nouveau ensemble à l'occasion ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 159 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 5 13 7 1 2]Ce sera tellement bon, que tu t'en lècheras les doigts ![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 2 1 25 25]OK... Ça devrait suffire ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 25 0 0]L'autre jour, j'ai vu une émission de cuisine à la télé qui montrait comment bien préparer du filet de poulet.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 26 0 0]Il faut le couper finement, le faire mariner dans une sauce et le faire mijoter à feu doux...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 27 0 0]Je vais faire honneur aux fourneaux aujourd'hui, tu verras ![n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Bonne chance.[e]
[uf 0 5 65278][uf 2 1]On verra, je suppose.[e]
[uf 0 5 65278][uf 2 1]Ça m'inquiète un peu.[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 28 0 0]Merci ! Tu peux compter sur moi.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 29 0 0]Ça va être tellement bon que tu vas en reprendre ![n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 159 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 2 10 25 25]Allez, aie un peu confiance en moi ! Je me suis renseignée pour m'améliorer, tu sais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 2 1 25 25]Je vais te montrer ce dont je suis vraiment capable. Faisons comme si la dernière fois n'avait jamais eu lieu, OK ?[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 159 65535 0 0][uf 3 1 1 0 0 32 0 0][uf 4 23 0 2 10 25 25]Hé, c'est pas sympa. Mais je suppose qu'après le fiasco de la dernière fois, je ne peux pas t'en vouloir...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 159 65535 0 0][uf 3 1 1 0 0 33 0 0][uf 4 23 0 2 2 25 25]C'est pour ça que je vais tout donner aujourd'hui. Je vais te montrer que je me suis améliorée.[n][uf 1 1][e]

[msg MSG_013_5_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 34 0 0][uf 4 23 0 2 1 25 25]Bon, commençons par nous laver les mains et... [uf 4 2], je te laisse t'occuper du riz et des légumes.[n][uf 1 1][e]

[msg MND_014_0_0]
[uf 0 5 65278][uf 2 1]J'ai préparé un sauté de poulet avec Yukari...[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 0 0 0 35 0 0][uf 4 23 0 2 1 25 25]Mmm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 36 0 0]La viande est si tendre et juteuse... Bien meilleure que la dernière fois ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 37 0 0]Tu vois ? Voilà ce dont je suis capable ! Je savais bien que j'y arriverais.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 38 0 0]Héhé, je vois bien que ça te plaît aussi, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 39 0 0][uf 5 13 7 1 2]La tête que tu fais en dit long ! Je n'ai pas pu m'empêcher de rire quand je t'ai vu engloutir tout ça.[n][uf 1 1][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 1 0 0 40 0 0][uf 4 23 0 2 0 25 25]Oh, mais... je ne t'ai pas entendu dire que tu te régalais...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 159 65535 0 0][uf 3 1 0 0 0 41 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 159 65535 0 0][uf 3 1 1 0 0 42 0 0][uf 4 23 0 2 1 25 25]Bref, bon appétit ! Oublie pas qu'il va encore falloir qu'on nettoie après ça.[n][uf 1 1][e]

