[msg MSG_000_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 1 0 0][uf 4 23 0 1 4 25 25]Ouah, cette bande-annonce était super épique ! J'aime bien les trucs étrangers.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0][uf 4 23 0 1 1 25 25]L'héroïne de cette série est connue pour être une femme forte.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 3 0 0][uf 4 23 0 1 3 25 25]La série m'intrigue depuis un moment, mais apparemment elle a un petit côté horreur aussi...[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Ça donne envie.[e]
[uf 0 5 65278][uf 2 1]Tu as peur ?[e]
[uf 0 5 65278][uf 2 1]Arg...[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 4 0 0][uf 4 23 0 1 4 25 25]Sérieux ?! Ça te dérange pas du tout ce genre de trucs ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0][uf 4 23 0 1 1 25 25]Parfait ! Je vais essayer de m'accrocher, dans ce cas.[n][uf 1 1][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 1 4 25 25]M-Moi ? Pff, b-bien sûr que non ! J'ai hâte de la regarder ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 7 0 0][uf 4 23 0 1 1 25 25]C'est juste que... c'est plus marrant de regarder ce genre de trucs avec quelqu'un, tu sais.[n][uf 1 1][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 8 0 0][uf 4 23 0 1 4 25 25]Attends... Tu crains l'horreur, toi aussi ?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 1 1 25 25]Euh, j-je veux dire... Moi, ça me dérange pas du tout. T'as rien à craindre tant qu'on regarde ça ensemble ![n][uf 1 1][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 10 0 0][uf 4 23 0 1 4 25 25]Oh, ça commence ! Je sens déjà la tension qui monte...[n][uf 1 1][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0][uf 4 23 0 1 0 25 25]Aaah, cette fin me donne tellement envie de savoir la suite ! Plus une série de zombies que d'horreur pure et dure finalement.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0][uf 4 23 0 1 1 25 25]L'héroïne était juste une fille ordinaire, mais elle a été capable de surmonter tellement d'épreuves... Je suis fan ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0][uf 4 23 0 1 1 25 25][uf 5 13 7 1 2]J'ai réussi à plus me concentrer sur l'histoire grâce à toi, [uf 4 2]. Je te dirais quand j'emprunterai le prochain épisode.[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]En observant le personnage principal, j'ai commencé à comprendre un peu mieux le [uf 4 30 1 1 1 0] d'un adulte...[n][uf 1 1][e]

[msg MSG_008_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0][uf 4 23 0 1 1 25 25]Pfiou... Je vais aller me coucher. Bonne nuit ![n][uf 1 1][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 1 0 25 25]Il y a toujours des retournements de situation incroyables dans cette série.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 16 0 0][uf 4 23 0 1 2 25 25]Quand la meilleure amie de l'héroïne l'a trahie... Ça m'a choqué ![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 17 0 0][uf 4 23 0 1 3 25 25]C'est horrible d'être trahi par la personne en qui on a le plus confiance.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0][uf 4 23 0 1 0 25 25]Qu'est-ce que tu ferais si ça t'arrivait ?[n][uf 1 1][e]

[sel SEL_010_0_0 top]
[uf 0 5 65278][uf 2 1]Peu m'importe.[e]
[uf 0 5 65278][uf 2 1]Je ne m'en remettrai pas.[e]
[uf 0 5 65278][uf 2 1]Il faut pardonner et tourner la page.[e]

[msg MSG_011_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 19 0 0][uf 4 23 0 1 1 25 25]Haha... Il n'y a clairement rien qui te dérange, toi, hein ? T'es vraiment quelqu'un de particulier, [uf 4 2].[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 1 3 25 25]J'ai vraiment du mal à voir les choses comme ça...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 1 3 25 25]Pas vraiment une trahison, mais ça m'a rappelé quand une fille dont j'étais proche a commencé à m'éviter du jour au lendemain.[n][uf 1 1][e]

[msg MSG_012_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 22 0 0][uf 4 23 0 1 3 25 25]Ouais... Pas besoin d'une grosse trahison. Si une amie commençait à me traiter différemment, ça me blesserait.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 23 0 0][uf 4 23 0 1 3 25 25]Ça m'est arrivé une fois. Une fille dont j'étais proche a commencé à m'éviter du jour au lendemain.[n][uf 1 1][e]

[msg MSG_013_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 24 0 0][uf 4 23 0 1 4 25 25][uf 4 2]... C'est vraiment admirable. On croirait entendre l'héroïne.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0][uf 4 23 0 1 3 25 25]Pour tout te dire, un jour, une fille dont j'étais proche a commencé à m'éviter du jour au lendemain.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 3 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 1 3 25 25]C'était pas une vraie trahison, mais ça m'a blessée quand même. C'est dur de pardonner, de tourner la page.[n][uf 1 1][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 27 0 0][uf 4 23 0 1 4 25 25]Bon sang, ça commence ! Il se passe tellement de trucs, faut vraiment bien suivre.[n][uf 1 1][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 4 65535 65535 0 0][uf 3 1 1 0 0 28 0 0][uf 4 23 0 1 4 25 25]C'est pas possible ! Me dis pas que ça va se terminer comme ça ?![n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 6 65535 65535 0 0][uf 3 1 1 0 0 29 0 0][uf 4 23 0 1 6 25 25]Arg, c'est chaque fois pareil... Ils sont vraiment bons pour pousser les gens à regarder la suite.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 2 65535 65535 0 0][uf 3 1 1 0 0 30 0 0][uf 4 23 0 1 2 25 25][uf 5 13 7 1 2]Je dois savoir comment ça va se terminer. On regardera la suite plus tard, OK ?[n][uf 1 1][e]

[msg MND_016_0_0]
[uf 0 5 65278][uf 2 1]En observant le personnage principal, j'ai commencé à comprendre un peu mieux le [uf 4 30 1 1 1 0] d'un adulte...[n][uf 1 1][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 31 0 0][uf 4 23 0 1 1 25 25]Il commence à se faire tard... On ferait mieux d'aller se coucher.[n][uf 1 1][e]

